[project]
name = "metro-hackathon"
version = "0.1.0"
description = "Baki Metrosu sernisin axini ve vaqon sixligi monitorinq sistemi"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24.0",
    "opencv-python>=4.8.0",
    "supervision>=0.20.0",
    "ultralytics>=8.0.0",
    "streamlit>=1.30.0",
]

